# Dependencies
markdown:        redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            BaishanCloud
tagline:          ''
description:      ''
url:              http://www.baishancloud.com
baseurl:          ''

author:
  name:           'BaishanCloud'
  url:            https://www.baishancloud.com


# Custom vars
version:          1.0.0

exclude:          ['node_modules']
